package main

import (
	"context"
	"encoding/json"
	"log"
	"math"
	"net/http"
	"strings"

	"github.com/MicahParks/keyfunc/v3"
	"github.com/golang-jwt/jwt/v5"
)

const (
	Port     = ":4003"
	Issuer   = "http://localhost:7080/auth"
	Audience = "client"
	JwksURL  = "http://localhost:7080/auth/oauth2/jwks"
)

type contextKey string
const (
	claimsKey   contextKey = "claims"
	rawTokenKey contextKey = "rawToken"
)

// CustomClaims matches the JWT payload generated by Nidam
type CustomClaims struct {
	Email       string   `json:"email"`
	Authorities []string `json:"authorities"`
	jwt.RegisteredClaims
}

type UserInfoDto struct {
	Username    string   `json:"username"`
	Email       string   `json:"email"`
	Authorities []string `json:"authorities"`
	Exp         int64    `json:"exp"`
}

func main() {
	// 1. Fetch public keys from Nidam Authorization Server
	jwks, err := keyfunc.NewDefault([]string{JwksURL})
	if err != nil {
		log.Fatalf("Failed to create JWKS from URL: %s", err)
	}

	mux := http.NewServeMux()

	// 2. Map Endpoints with Security Middlewares
	mux.HandleFunc("GET /me", authenticateToken(jwks, meHandler))
	
	mux.HandleFunc("GET /demo", authenticateToken(jwks, 
		requireAuth(hasAnyAuthority([]string{"manage-users", "manage-projects"}, demoHandler))))
	
	mux.HandleFunc("GET /top-secret", authenticateToken(jwks, 
		requireAuth(hasAnyAuthority([]string{"top-secret"}, topSecretHandler))))

	log.Printf("Go Resource Server listening on port %s\n", Port)
	log.Fatal(http.ListenAndServe(Port, mux))
}

// --- Middlewares ---

// Extracts and validates the JWT, storing claims and raw token in context
func authenticateToken(jwks keyfunc.Keyfunc, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		authHeader := r.Header.Get("Authorization")
		if !strings.HasPrefix(authHeader, "Bearer ") {
			next.ServeHTTP(w, r) // Proceed anonymously
			return
		}

		rawToken := strings.TrimPrefix(authHeader, "Bearer ")
		token, err := jwt.ParseWithClaims(rawToken, &CustomClaims{}, jwks.Keyfunc)

		if err != nil || !token.Valid {
			http.Error(w, `{"error": "Unauthorized", "message": "Invalid token"}`, http.StatusUnauthorized)
			return
		}

		claims, ok := token.Claims.(*CustomClaims)
		if !ok {
			http.Error(w, `{"error": "Unauthorized"}`, http.StatusUnauthorized)
			return
		}

		// Validate Issuer and Audience
		iss, _ := claims.GetIssuer()
		if iss != Issuer {
			http.Error(w, `{"error": "Invalid Issuer"}`, http.StatusUnauthorized)
			return
		}

		auds, _ := claims.GetAudience()
		validAud := false
		for _, aud := range auds {
			if aud == Audience {
				validAud = true
				break
			}
		}
		if !validAud {
			http.Error(w, `{"error": "Invalid Audience"}`, http.StatusUnauthorized)
			return
		}

		ctx := context.WithValue(r.Context(), claimsKey, claims)
		ctx = context.WithValue(ctx, rawTokenKey, rawToken)
		next.ServeHTTP(w, r.WithContext(ctx))
	}
}

// Ensures the user is authenticated
func requireAuth(next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		if r.Context().Value(claimsKey) == nil {
			http.Error(w, `{"error": "Authentication required"}`, http.StatusUnauthorized)
			return
		}
		next.ServeHTTP(w, r)
	}
}

// Enforces RBAC checks against JWT claims
func hasAnyAuthority(allowed []string, next http.HandlerFunc) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		claims := r.Context().Value(claimsKey).(*CustomClaims)
		
		hasMatch := false
		for _, userAuth := range claims.Authorities {
			for _, allowedAuth := range allowed {
				if userAuth == allowedAuth {
					hasMatch = true
					break
				}
			}
		}

		if !hasMatch {
			w.Header().Set("Content-Type", "application/json")
			w.WriteHeader(http.StatusForbidden)
// 			w.Write([]byte(`{"code": "ACCESS_DENIED", "message": "Insufficient permissions"}`))
			w.Write([]byte(`{"status": 403, "code": "ACCESS_DENIED", "message": "You do not have sufficient permissions"}`))
			return
		}
		next.ServeHTTP(w, r)
	}
}

// --- Route Handlers ---

func meHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	claims, ok := r.Context().Value(claimsKey).(*CustomClaims)

	if !ok {
		json.NewEncoder(w).Encode(UserInfoDto{
			Username: "", Email: "", Authorities: []string{}, Exp: math.MaxInt64,
		})
		return
	}

	exp, _ := claims.GetExpirationTime()
	sub, _ := claims.GetSubject()
	auths := claims.Authorities
	if auths == nil {
		auths = []string{} // Prevent null in JSON output
	}

	json.NewEncoder(w).Encode(UserInfoDto{
		Username:    sub,
		Email:       claims.Email,
		Authorities: auths,
		Exp:         exp.Unix(),
	})
}

func demoHandler(w http.ResponseWriter, r *http.Request) {
	w.Header().Set("Content-Type", "application/json")
	claims := r.Context().Value(claimsKey).(*CustomClaims)
	rawToken := r.Context().Value(rawTokenKey).(string)
	
	auths := claims.Authorities
	if auths == nil {
		auths = []string{}
	}

	json.NewEncoder(w).Encode(map[string]interface{}{
		"tokenValue":  rawToken,
		"claims":      claims,
		"authorities": auths,
	})
}

func topSecretHandler(w http.ResponseWriter, r *http.Request) {
	w.Write([]byte("Top secret information"))
}