scheme: http
hostname: localhost
reverse-proxy-port: 7080
reverse-proxy-uri: ${scheme}://${hostname}:${reverse-proxy-port}
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}

security:
  permit-all:
    - /me
    - /actuator/health/**
    - /docs/**

resource-server-port: 4003
audience: client

server:
  port: ${resource-server-port}
  forward-headers-strategy: framework

spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${issuer}

#trace: true