#Mon Sep 07 20:53:26 UTC 2026
micronaut:
  application:
    name: nidam-resource-server
  server:
    port: 4003
  security:
    authentication: bearer
    token:
      roles-name: authorities # Maps Nidam's JWT 'authorities' array to @Secured
      jwt:
        signatures:
          jwks:
            nidam:
              url: http://localhost:7080/auth/oauth2/jwks
        claims-validators:
          audience: client
          issuer: http://localhost:7080/auth
