authorization-server-name: token-generator

host: http://localhost
browser-facing-domain: http://localhost
# for docker purposes, this must stay whatever the domain name is. in development it is localhost, wheareas the internal is the container name TODO test
# for now always use internal.

# MySQL
#users-db-url: jdbc:mysql://localhost:3306/identity_hub
#users-db-user: root
#users-db-password: "CcmN*`6@3T9H%P#yg^V<7v"
# Embedded H2
#users-db-url: jdbc:h2:tcp://localhost:9092/identity_hub
#users-db-user: nidam
#users-db-password: "gF2mshbI819AV2L3"

# Mongo
users-db-url: mongodb://localhost:27017/identity_hub

password-encoders: scrypt,bcrypt,argon2,pbkdf2
password-idless: scrypt

reverse-proxy-port: 7080
reverse-proxy-uri: ${host}:${reverse-proxy-port}

authorization-server-port: 4002
authorization-server-prefix: /auth
issuer: ${reverse-proxy-uri}${authorization-server-prefix}

bff-prefix: /bff
react-prefix: /react-ui
bff-post-logout-endpoint: /post-logout

client:
  id: client
  secret-hash: '{bcrypt}$2a$10$.ld6BfZescPDfVVduvu.6O9.7FLMI64l4PfvnBZJQEBhTLFFbeKei'  #value is 'secret', must use hash because of password encoders
  internal-identifier: nidam-bff-internal-id
  login-uri: ${reverse-proxy-uri}${bff-prefix}/login/oauth2/code/${authorization-server-name}   # Explanation below
#  localhost here because this is the same as bff\src\main\resources\application.yml, for docker purposes.
  logout-uri: ${reverse-proxy-uri}${react-prefix}
  bff-post-logout-uri: ${reverse-proxy-uri}${bff-prefix}${bff-post-logout-endpoint}     # TODO this change will break docker-compose.yml: update file


server:
  port: ${authorization-server-port}
  servlet:
    contextPath: ${authorization-server-prefix}
    session:
      timeout: 12h
  forward-headers-strategy: framework

# first in the list is the default encoder
custom:
  password:
    encoders: ${token-generator.password-encoders:${password-encoders}}
    idless: ${token-generator.password-idless:${password-idless}}    # encoder for hashes without {id}

spring:
  datasource:
    url: ${token-generator.users-db-url:${users-db-url}}
    username: ${token-generator.users-db-user:${users-db-user}}
    password: ${token-generator.users-db-password:${users-db-password}}
  config:
    import: optional:file:./configuration.yml
  profiles:
    active: ${nidam.persistence-mode}
    group:
      dev-sql:
        - dev
        - sql
      dev-mongo:
        - dev
        - mongo
  data:
    redis:
      host: localhost
      port: 6379
      repositories:
        enabled: false
  session:
    timeout: 12h
    redis:
      namespace: nidam:token-generator

rate-limiter:
  enabled: true
  lockout-duration: 5    # minutes
  max-attempts: 5
  cleanup-interval-ms: 60000      # miliseconds

# options: sql, mongo . default: sql . When changing don't forget to update ${users-db-url/username/password},
#  also update nidam-dev.ps1 -Command "mvn spring-boot:run '-Dspring-boot.run.profiles=dev-mongo'"
nidam:
  persistence-mode: "mongo"

management:
  endpoints:
    access:
      default: none

#logging:
#  level:
    # Enable TRACE logging for Redis
#    root: INFO
#    org.springframework.data.redis: TRACE
#    org.springframework.session.data.redis: TRACE
#    io.lettuce.core: TRACE
#    org.springframework.cache: TRACE
#    org.springframework: INFO
#    org.springframework.security: INFO
#    org.springframework.security.oauth2: INFO
#    org.springframework.web: INFO
#    reactor.netty: INFO
#    io.netty: INFO
#    io.projectreactor:
#    org.apache.tomcat: INFO
#    org.springframework.boot: INFO
#    org.springframework.beans: INFO
#    org.apache.catalina.session.ManagerBase: INFO
#trace: true
