spring:
  application:
    name: spa-server
  config:
    import: optional:file:./configuration.yml

server:
  port: ${react-port}


# for spa config
host: http://localhost
registration-prefix: /registration
registration-uri: ${reverse-proxy-uri}${registration-prefix}

react-port: 4001
react-prefix: /react-ui
reverse-proxy-port: 7080
reverse-proxy-uri: ${host}:${reverse-proxy-port}
react-proxy-uri: ${reverse-proxy-uri}${react-prefix}

bff-prefix: /bff
bff-resource-server-route-prefix: /api
bff-proxy-uri: ${reverse-proxy-uri}${bff-prefix}
resource-server-through-bff-proxy-uri: ${bff-proxy-uri}${bff-resource-server-route-prefix}

react-login-url: ${bff-proxy-uri}/oauth2/authorization/token-generator
react-logout-url: ${bff-proxy-uri}/logout

profile-public-endpoint: /me
recaptcha-enabled: 'false'
recaptcha-key: 6LcyyEMpAAAAAMztnW6xVq1HFD0b-mlyk2t6NZa-

nidam:
  protocol: http