registration-port: 4000

users-db-url: jdbc:mysql://localhost:3306/identity_hub
users-db-user: root
users-db-password: "CcmN*`6@3T9H%P#yg^V<7v"

#users-db-url: jdbc:h2:file:./db/identity_hub
#users-db-url: jdbc:h2:tcp://localhost:9092/identity_hub
#users-db-user: nidam
#users-db-password: "gF2mshbI819AV2L3"
#users-db-user: sa
#users-db-password: ""

# Mongo
#users-db-url: mongodb://localhost:27017/identity_hub

authorities: manage-users,manage-projects
password-encoders: scrypt,bcrypt,argon2,pbkdf2
password-idless: scrypt

recaptcha-secret: "6LcyyEMpAAAAANm0qZB6kzDQRT5Li4FSGCTe8ESf"
allowed-cors-uri: http://localhost:4001,http://127.0.0.1:4001,http://localhost:7080,http://127.0.0.1:7080

server:
  port: ${registration-port}
  error:
    include-message: always
management:
  endpoints:
    access:
      default: none

spring:
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
  config:
    import: optional:file:./configuration.yml
  profiles:
    active: ${nidam.persistence-mode}
    group:
      dev-sql:
        - dev
        - sql
      dev-mongo:
        - dev
        - mongo

custom:
  authorization:
    authorities: ${registration.authorities:${authorities}}
    roles:
      - ADMIN
      - MANAGER
      - USER
    authType: 1
  password:
    encoders: ${registration.password-encoders:${password-encoders}}
    idless: ${registration.password-idless:${password-idless}}
  recaptcha:
    secret: ${registration.recaptcha-secret:${recaptcha-secret}}
  allowed-cors-uri: ${registration.allowed-cors-uri:${allowed-cors-uri}}

# options: sql, mongo . default: sql . When changing don't forget to update ${users-db-url/username/password}
nidam:
  persistence-mode: "sql"


