## Custom properties to ease configuration overrides
## on command-line or IDE launch configurations
host: http://localhost
reverse-proxy-port: 7080

react-port: 4001
react-prefix: /react-ui
react-uri: ${host}:${react-port}${react-prefix}

authorization-server-port: 4002
authorization-server-prefix: /auth
authorization-server-uri-no-context-path: ${host}:${authorization-server-port}
authorization-server-uri: ${host}:${authorization-server-port}${authorization-server-prefix}

authorization-server-load-balancer-uri: lb://token-generator
authorization-server-health-check-path: ${authorization-server-prefix}/actuator/health

bff-port: 7081
bff-prefix: /bff
bff-uri: ${host}:${bff-port}
bff-load-balancer-uri: lb://bff
bff-health-check-path: /actuator/health

server:
  port: ${reverse-proxy-port}
  forward-headers-strategy: framework
management:
  endpoints:
    access:
      default: none

spring:
  config:
    import: optional:file:./configuration.yml
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - AddResponseHeader=X-Frame-Options, DENY
            - AddResponseHeader=X-Content-Type-Options, nosniff
            - AddResponseHeader=Referrer-Policy, no-referrer
          routes:
            # SPAs assets
            - id: react-ui
              uri: ${react-uri}
              predicates:
                - Path=${react-prefix}/**       # Changed because of docker: last chance
              filters:
                - PreserveHostHeader    #  must explicitly enable forwarded header handling
                # next: tells the downstream application (like your authorization server or BFF) what the original scheme of the client request was — usually either http or https
                - AddRequestHeader=X-Forwarded-Proto, http
            # Authorization-server
            - id: authorization-server
#              uri: ${authorization-server-uri}
              uri: ${authorization-server-load-balancer-uri}   # Load balancer URI, for multiple instances of the authorization server
              predicates:
                - Path=${authorization-server-prefix}/**
              filters:
                - PreserveHostHeader            # Without PreserveHostHeader, the forwarded Host becomes localhost:4002
                - AddRequestHeader=X-Forwarded-Proto, http
            # BFF
            - id: bff
#              uri: ${bff-uri}
              uri: ${bff-load-balancer-uri} # Load balancer URI, for multiple instances of the BFF
              predicates:
                - Path=${bff-prefix}/**
              filters:
                - StripPrefix=1
                - PreserveHostHeader
                - AddRequestHeader=X-Forwarded-Proto, http
    discovery:
      client:
        simple:
          instances:
            token-generator:
              - uri: ${authorization-server-uri}
#              - uri: http://localhost:4010/auth
            bff:
              - uri: ${bff-uri}
#              - uri: http://localhost:7082
    loadbalancer:
      health-check:
        initial-delay: 0
        interval: 5s
        path:
          token-generator: ${authorization-server-health-check-path}
          bff: ${bff-health-check-path}

#trace: true